theme: jekyll-theme-leap-day
title: VTEX SDK (.NET)
description: ğŸ›’ âš™ï¸ VTEX platform .NET SDK
logo: https://raw.githubusercontent.com/guibranco/VTEX-SDK-dotnet/main/packageLogo.png
show_downloads: true
